# Generated by Django 4.0.7 on 2022-09-07 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=225, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('superuser', models.BooleanField(default=False)),
                ('staff', models.BooleanField(default=False)),
                ('date_joined', models.TimeField(auto_now_add=True)),
                ('phone', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
