# Generated by Django 4.1 on 2022-08-30 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="offer",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
