# Generated by Django 4.1 on 2022-08-30 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_category_offer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="title",
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
