# Generated by Django 4.1 on 2022-08-31 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0004_alter_category_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image1",
            field=models.ImageField(upload_to="image"),
        ),
        migrations.AlterField(
            model_name="product",
            name="image2",
            field=models.ImageField(upload_to="image"),
        ),
        migrations.AlterField(
            model_name="product",
            name="image3",
            field=models.ImageField(upload_to="image"),
        ),
        migrations.AlterField(
            model_name="product",
            name="image4",
            field=models.ImageField(upload_to="image"),
        ),
    ]
