# Generated by Django 4.0.7 on 2022-09-07 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_remove_cartitem_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
