# Generated by Django 4.0.7 on 2022-09-30 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_coupons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupons',
            name='coupon_min',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='coupons',
            name='coupon_offer',
            field=models.IntegerField(),
        ),
    ]
