# Generated by Django 4.1.5 on 2023-02-04 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="faculty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, null=True)),
                ("address", models.TextField(null=True)),
                ("photo", models.ImageField(null=True, upload_to="")),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")],
                        max_length=1,
                        null=True,
                    ),
                ),
                ("district", models.CharField(max_length=255, null=True)),
                ("contact_number_2", models.CharField(max_length=10, null=True)),
                ("whatsapp_contact_number", models.CharField(max_length=10, null=True)),
                ("date_of_birth", models.DateField(null=True)),
                ("qualification", models.CharField(max_length=255, null=True)),
                (
                    "experiances",
                    models.CharField(
                        blank=True,
                        choices=[("1", "Offline"), ("2", "Online")],
                        max_length=1,
                        null=True,
                    ),
                ),
                ("experiance_link", models.URLField(blank=True, null=True)),
                (
                    "mode_of_class",
                    models.CharField(
                        blank=True,
                        choices=[("O", "Offline"), ("L", "Online"), ("B", "Both")],
                        max_length=1,
                        null=True,
                    ),
                ),
                ("email", models.EmailField(max_length=254, null=True, unique=True)),
                ("password", models.CharField(max_length=120, null=True)),
                ("joined_date", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_login", models.DateTimeField(auto_now=True, null=True)),
                ("is_staff", models.BooleanField(default=False, null=True)),
                ("is_active", models.BooleanField(default=False, null=True)),
                ("is_verified", models.BooleanField(default=False, null=True)),
            ],
        ),
    ]
