# Generated by Django 4.1.5 on 2023-02-01 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_superadmin_course_user_topic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='topic',
            new_name='module',
        ),
    ]
