# Generated by Django 4.0.7 on 2022-09-07 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0009_delete_cart'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('1', 'COD'), ('2', 'UPI')], max_length=200)),
                ('payment_status', models.BooleanField(default=False)),
                ('delivery_status', models.CharField(choices=[('P', 'Pending'), ('S', 'Shipped'), ('D', 'Deliverd')], max_length=200)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.cartitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Billing_address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.TextField(max_length=10)),
                ('email', models.EmailField(max_length=225)),
                ('address1', models.TextField(max_length=250)),
                ('address2', models.TextField(max_length=250)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('state', models.CharField(max_length=250)),
                ('zip', models.IntegerField()),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='order.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
