# Generated by Django 4.0.7 on 2022-09-08 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_remove_order_product_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing_address',
            name='country',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='billing_address',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
