# Generated by Django 4.0.7 on 2022-09-18 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_order_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing_address',
            name='order_id_Ref',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='payment',
            name='order_id',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
