# Generated by Django 4.0.7 on 2022-09-20 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_billing_address_order_id_ref_payment_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing_address',
            name='order_id_Ref',
            field=models.CharField(default=None, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default=None, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order_id',
            field=models.CharField(default=None, max_length=200, unique=True),
        ),
    ]
