# Generated by Django 4.0.7 on 2022-09-27 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_alter_billing_address_order_id_ref_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
